# Generated by Django 4.1.6 on 2023-02-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_realtor_account'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.realtor'),
        ),
    ]
