# Generated by Django 4.1.6 on 2023-02-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_apartment_parking_apartment_pet_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='total_floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='total_floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
