# Generated by Django 4.1.6 on 2023-02-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_apartment_floor_apartment_total_floor_room_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='tenant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tenant_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='tenant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='tenant_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
