# Generated by Django 4.1.6 on 2023-02-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_shop_officetel_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='land_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='parking_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='under_floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='premium',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
