# Generated by Django 4.1.6 on 2023-02-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_building_land_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='area_total_floor_area',
            new_name='area_total_floor',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='area_total_floor_area_for_ratio',
            new_name='area_total_floor_for_ratio',
        ),
    ]
