# Generated by Django 4.1.6 on 2023-02-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_rename_area_total_floor_area_building_area_total_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='owner_phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='tenant_phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='owner_phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='officetel',
            name='owner_phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='officetel',
            name='tenant_phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='owner_phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='tenant_phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner_phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='tenant_phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
    ]
