# Generated by Django 4.1.6 on 2023-02-23 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_apartment_management_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='addres_detail',
            new_name='address_detail',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='addres_detail',
            new_name='address_detail',
        ),
        migrations.RenameField(
            model_name='officetel',
            old_name='addres_detail',
            new_name='address_detail',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='addres_detail',
            new_name='address_detail',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='addres_detail',
            new_name='address_detail',
        ),
    ]
