# Generated by Django 4.1.6 on 2023-03-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_rename_addres_detail_apartment_address_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='loanable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('progress', 'progress'), ('finished', 'finished')], default='progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='building',
            name='loanable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='building',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='building',
            name='status',
            field=models.CharField(choices=[('progress', 'progress'), ('finished', 'finished')], default='progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='officetel',
            name='loanable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='officetel',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='officetel',
            name='status',
            field=models.CharField(choices=[('progress', 'progress'), ('finished', 'finished')], default='progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='loanable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('progress', 'progress'), ('finished', 'finished')], default='progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='loanable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('progress', 'progress'), ('finished', 'finished')], default='progress', max_length=20),
        ),
    ]
